import type {EditorThemeClasses} from 'lexical';

import './MemoryMapTheme.css';

const theme: EditorThemeClasses = {
  blockCursor: 'MemoryMapTheme__blockCursor',
  characterLimit: 'MemoryMapTheme__characterLimit',
  code: 'MemoryMapTheme__code',
  codeHighlight: {
    atrule: 'MemoryMapTheme__tokenAttr',
    attr: 'MemoryMapTheme__tokenAttr',
    boolean: 'MemoryMapTheme__tokenProperty',
    builtin: 'MemoryMapTheme__tokenSelector',
    cdata: 'MemoryMapTheme__tokenComment',
    char: 'MemoryMapTheme__tokenSelector',
    class: 'MemoryMapTheme__tokenFunction',
    'class-name': 'MemoryMapTheme__tokenFunction',
    comment: 'MemoryMapTheme__tokenComment',
    constant: 'MemoryMapTheme__tokenProperty',
    deleted: 'MemoryMapTheme__tokenProperty',
    doctype: 'MemoryMapTheme__tokenComment',
    entity: 'MemoryMapTheme__tokenOperator',
    function: 'MemoryMapTheme__tokenFunction',
    important: 'MemoryMapTheme__tokenVariable',
    inserted: 'MemoryMapTheme__tokenSelector',
    keyword: 'MemoryMapTheme__tokenAttr',
    namespace: 'MemoryMapTheme__tokenVariable',
    number: 'MemoryMapTheme__tokenProperty',
    operator: 'MemoryMapTheme__tokenOperator',
    prolog: 'MemoryMapTheme__tokenComment',
    property: 'MemoryMapTheme__tokenProperty',
    punctuation: 'MemoryMapTheme__tokenPunctuation',
    regex: 'MemoryMapTheme__tokenVariable',
    selector: 'MemoryMapTheme__tokenSelector',
    string: 'MemoryMapTheme__tokenSelector',
    symbol: 'MemoryMapTheme__tokenProperty',
    tag: 'MemoryMapTheme__tokenProperty',
    url: 'MemoryMapTheme__tokenOperator',
    variable: 'MemoryMapTheme__tokenVariable',
  },
  embedBlock: {
    base: 'MemoryMapTheme__embedBlock',
    focus: 'MemoryMapTheme__embedBlockFocus',
  },
  hashtag: 'MemoryMapTheme__hashtag',
  heading: {
    h1: 'MemoryMapTheme__h1',
    h2: 'MemoryMapTheme__h2',
    h3: 'MemoryMapTheme__h3',
    h4: 'MemoryMapTheme__h4',
    h5: 'MemoryMapTheme__h5',
    h6: 'MemoryMapTheme__h6',
  },
  image: 'editor-image',
  indent: 'MemoryMapTheme__indent',
  inlineImage: 'inline-editor-image',
  layoutContainer: 'MemoryMapTheme__layoutContaner',
  layoutItem: 'MemoryMapTheme__layoutItem',
  link: 'MemoryMapTheme__link',
  list: {
    listitem: 'MemoryMapTheme__listItem',
    listitemChecked: 'MemoryMapTheme__listItemChecked',
    listitemUnchecked: 'MemoryMapTheme__listItemUnchecked',
    nested: {
      listitem: 'MemoryMapTheme__nestedListItem',
    },
    olDepth: [
      'MemoryMapTheme__ol1',
      'MemoryMapTheme__ol2',
      'MemoryMapTheme__ol3',
      'MemoryMapTheme__ol4',
      'MemoryMapTheme__ol5',
    ],
    ul: 'MemoryMapTheme__ul',
  },
  ltr: 'MemoryMapTheme__ltr',
  mark: 'MemoryMapTheme__mark',
  markOverlap: 'MemoryMapTheme__markOverlap',
  paragraph: 'MemoryMapTheme__paragraph',
  quote: 'MemoryMapTheme__quote',
  rtl: 'MemoryMapTheme__rtl',
  table: 'MemoryMapTheme__table',
  tableAddColumns: 'MemoryMapTheme__tableAddColumns',
  tableAddRows: 'MemoryMapTheme__tableAddRows',
  tableCell: 'MemoryMapTheme__tableCell',
  tableCellActionButton: 'MemoryMapTheme__tableCellActionButton',
  tableCellActionButtonContainer:
    'MemoryMapTheme__tableCellActionButtonContainer',
  tableCellEditing: 'MemoryMapTheme__tableCellEditing',
  tableCellHeader: 'MemoryMapTheme__tableCellHeader',
  tableCellPrimarySelected: 'MemoryMapTheme__tableCellPrimarySelected',
  tableCellResizer: 'MemoryMapTheme__tableCellResizer',
  tableCellSelected: 'MemoryMapTheme__tableCellSelected',
  tableCellSortedIndicator: 'MemoryMapTheme__tableCellSortedIndicator',
  tableResizeRuler: 'MemoryMapTheme__tableCellResizeRuler',
  tableSelected: 'MemoryMapTheme__tableSelected',
  tableSelection: 'MemoryMapTheme__tableSelection',
  text: {
    bold: 'MemoryMapTheme__textBold',
    code: 'MemoryMapTheme__textCode',
    italic: 'MemoryMapTheme__textItalic',
    strikethrough: 'MemoryMapTheme__textStrikethrough',
    subscript: 'MemoryMapTheme__textSubscript',
    superscript: 'MemoryMapTheme__textSuperscript',
    underline: 'MemoryMapTheme__textUnderline',
    underlineStrikethrough: 'MemoryMapTheme__textUnderlineStrikethrough',
  },
};

export default theme;