export default {
    'GET_OPENID_CONFIGURATION_SUCCESS': 'GET_OPENID_CONFIGURATION_SUCCESS',
    'SESSION_SUCCESS': 'SESSION_SUCCESS',
    'ME_STATE_UPDATE': 'ME_STATE_UPDATE',
    //CONSTANTS FOR MESTORE
    'UPDATE_LANGUAGE': 'UPDATE_LANGUAGE',
    'REFRESH_TOKEN_SUCCESS': 'REFRESH_TOKEN_SUCCESS',
    'GET_FEATURE_VERSION': 'GET_FEATURE_VERSION',
    'GET_BOOT_SETTINGS': 'GET_BOOT_SETTINGS',
    'USER_INFO_SUCCESS': 'USER_INFO_SUCCESS',
    'SET_DEFAULT_CONTRACTS': 'SET_DEFAULT_CONTRACTS',
    'SET_USER_TYPE': 'SET_USER_TYPE',
    'XHR_CALL_INPROGRESS': 'XHR_CALL_INPROGRESS',
    'XHR_CALL_END': 'XHR_CALL_END',
    'ACCOUNT_USER_DETAILS_UPDATE': 'ACCOUNT_USER_DETAILS_UPDATE',
    'EDITOR_INFO_UPDATE': 'EDITOR_INFO_UPDATE',
    'DELETED_NODES': 'DELETED_NODES'
    //login State 

};